import Navbar from './Components/Navbar'
import './globals.css'
import { Mulish } from 'next/font/google';
import Footer   from './Components/Footer';

const mulish = Mulish({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
});

export const metadata = {
  title: "Joy's webflix",
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Navbar />
        {children}
       <Footer/>
      </body>
     
    </html>
  )
}
